# Exercise 5.A NumPy fundamentals
## Working with NumPy Arrays
### Author: Luis Angel Espinosa Villicana

In [1]:
import numpy as np

## Array Basics

In [12]:
fruits = ["apple", "banana", "cherry", "date"]

In [13]:
arr_1 = np.array(fruits)
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [22]:
for entry in arr_1:
    print(type(entry)) # Returns data type as list
    print(entry.dtype) # dtype returns the actual data type (unicode) of the characters within the string and number of characters in string


<class 'numpy.str_'>
<U5
<class 'numpy.str_'>
<U6
<class 'numpy.str_'>
<U6
<class 'numpy.str_'>
<U4


In [24]:
arr_2 = np.array([(10, 11, 12), (13, 14, 15)])
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [25]:
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [26]:
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [27]:
arr_3 = np.array([(1, 3, 5), (2, 4, 6)])
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [35]:
arr_4 = np.array((arr_3[0,2], arr_3[1,1]))
print(arr_4)

[5 4]


In [37]:
arr_5 = np.array([[[1,1],[1,1]],[[1,1],[1,1]]])
print(arr_5)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
