# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np

## Looping Through Arrays

* In a new code cell, create a variable named arrA as a two-dimensional array
containing (11, 12, 13) and (14, 15, 16) then print arrA.

In [3]:
arrA = np.array([(11, 12, 13) , (14, 15, 16)])

print(arrA)

[[11 12 13]
 [14 15 16]]


* In a new code cell, loop through the first dimension of arrA (i.e. for x in arrA) and
print each element multiplied by 2.

In [4]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


* In a new code cell, loop through the second dimension of arrA (i.e. for y in x) and
print each element multiplied by 2.

In [5]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


* Add a markdown cell. In your own words describe the difference between the
results for first loop and the second loop.

In the first loop, the values are still being contained in a list because we only iterated through the first layer of the array. The second loop prints the values individually because they are access through a second iteration.

* Add another code cell. Again loop through the second dimension of arrA (i.e. for y
in x), but this time, assign x*2 to a variable named loop_result. Add another line
of code to print loop_result, then add a comment to the cell to explain how/why
this result is different.

In [16]:
for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


This result is different because for each value that is in the second dimension, we are doubling the list it belongs to and printing out the list rather than the value itself. We seem the same list printed 3 times because there are 3 values within each list.

## Joining and Stacking Arrays

* Create variable joined_array_1 and assign it the value of arrA concatenated
with arrA on axis=0 (the default axis). Print joined_array_1.

In [17]:
joined_array_1 = np.concatenate((arrA, arrA))
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


* Create variable joined_array_2 and assign it the value of arrA concatenated
with arrA on axis=1. Print joined_array_2.

In [18]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


* Create variable stacked_array_1 and assign it the value of joined_array_1
stacked with joined_array_1 on the default axis. Print stacked_array_1.

In [21]:
stacked_array_1 = np.concatenate((joined_array_1, joined_array_1))
print(stacked_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


* Create variable stacked_array_2 and assign it the value of joined_array_1
stacked with joined_array_2 on the default axis. What error message do you
get? Add a comment to the cell to explain the error that comes back.

In [24]:
stacked_array_2 = np.concatenate((joined_array_1, joined_array_2))
# We got a ValueError message because the dimensions of the arrays outside of the concatenation axis do not match.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 6

* Create variable another_joined_array and assign it the value of
joined_array_1 concatenated with arrA. Print another_joined_array.

In [26]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


* Create variable another_2 and again assign it the value of joined_array_1
concatenated with arrA, but this time on axis=1. What happens when you try to run
this? Add a comment to the cell to paraphrase the error message in your own
words.

In [27]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1)
# We get a ValueError because the column length of joined_array_1 is longer than the row length of arrA and if concatenated, the shape of the new array
# would be incomplete.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

* Create a cell with three new variables (named as you choose). In each variable, use
either the hstack(), vstack(), or dstack() function to stack arrA with arrA.
Add a comment after each that explains what the function is doing. Print the results
of each variable.

In [36]:
line_break = '----------------------------------------------------------------------------------------'
h = np.hstack((arrA, arrA)) #adds the array on the horizontal axis, I believe the column amount must match
print(h)
print(line_break)
v = np.vstack((arrA, arrA)) #adds the array on the vertical axis, rows must match in length
print(v)
print(line_break)
d = np.dstack((arrA, arrA)) #Inserts the 2nd array in-between the first pairing values based on their index in their own array 
# and shifts the arrays axis and stacks along the depth axis. Automatically forces the array into a 3-dimensional array 
print(d)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
----------------------------------------------------------------------------------------
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
----------------------------------------------------------------------------------------
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

* Create variable splitsky and assign it the value of joined_array_1 split into 2.
Print the variable. Then add a comment to the cell to describe the result: how many
arrays? Of how many dimensions each?

In [37]:
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)
# Our joined array 1 was split into two arrays of 2x3 dimensions at the default axis 0

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


* Create variable spliterino and assign it the value of joined_array_1 split
into 3. Print the variable. Then add a comment to the cell to describe the result: how
many arrays? Of how many dimensions each?

In [39]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)
# joined_array_1 was split into 3 arrays of unequal dimensions because of insufficient values
# first array is 2x3 while the the last two are 1x3

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


 ## Searching and Replacing Array Values

* In a code cell, create variable result_1. For the value of this variable, use where()
to find each even number within arrA (hint, you’ll need to write a condition using %
and ==). If the condition is met, print the value from arrA; if not met, print 'odd'.
Print result_1.

In [46]:
print(arrA)
print(line_break)
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[[11 12 13]
 [14 15 16]]
----------------------------------------------------------------------------------------
[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

* Create variable arrB as a 2-D array including the values (7,6), (13,5), and (7,3).
Create another variable, arrB_sorted, and assign it the sorted value of arrB.
Print arrB_sorted.

In [51]:
arrB = np.array( [ (7,6) , (13,5) , (7,3) ] )
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


* Finally, let’s filter arrB using conditional logic. Start the cell with a print statement
to again print the contents of arrB. Then create variable z with the value arrB < 7
to look for values less than 7. Next create variable arrC, and assign it arrB[z].
Print arrC.

In [53]:
print(arrB)
print(line_break)
z = arrB < 7
arrC = arrB[z]
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
----------------------------------------------------------------------------------------
[6 5 3]


* Applying the same sort of structure, how would you create a new conditional logic
filter y to look for values greater than or equal to 7? Follow similar steps as above to
create a new variable arrD to hold the filtered results, and print arrD.

In [54]:
t = arrB >= 7
arrT = arrB[t]
print(arrT)

[ 7 13  7]
