## Exercise 1.B NumPy Random

In [4]:
import numpy as np

## Generating Random Numbers

Create a variable named r_1 that contains a random set of integers between 1 and
20 with a size of 2 elements. Print r_1.

In [7]:
r_1 = np.random.randint(1, 20, size=(2))
print(r_1)

[ 1 11]


Create a variable named r_2 that contains a random set of integers between 1 and
20 with a size of 1 row, 2 columns. Print r_2.

In [9]:
r_2 = np.random.randint(1, 20, size=(1, 2))
print(r_2)

[[3 7]]


Create a variable named r_3 that contains a random set of floats between 0 and 1
with a size of 2 rows, 1 columns. Print r_3.

In [13]:
r_3 = np.random.rand(2, 1)
print(r_3)

[[0.43289146]
 [0.34149375]]


Create a variable named r_4 that contains a random set of integers between 20
and 100 with a size of 4 rows, 5 columns. Print r_4.

In [15]:
r_4 = np.random.randint(20, 100, size=(4, 5))
print(r_4)

[[68 22 84 50 51]
 [90 81 57 24 68]
 [28 91 30 58 33]
 [74 28 46 59 46]]


Create a variable named r_5 that contains a random set of floats between 0 and 1
with a size of 4 rows, 5 columns. Print r_5.

In [16]:
r_5 = np.random.rand(4, 5)
print(r_5)

[[0.31695893 0.37666479 0.67462719 0.21479601 0.20350421]
 [0.23904576 0.43141483 0.05295425 0.33187506 0.69025403]
 [0.21518381 0.25203146 0.77482089 0.62656103 0.75454361]
 [0.92414125 0.41656327 0.52910179 0.10953937 0.75433675]]


## Generating Random Choices from an Array

Create a variable named students and assign it a 1-D array containing the names
of 12 of your classmates.

In [17]:
students = np.array(['Edmund', 'Brandon', 'Kevin', 'Dahlia', 'Natalia', 'Destiny', 'Jeremiah', 'Hritik', 'Stefhanie', 'Luis', 'Bess', 'James Bond'])

Create a variable named call_on and use it to choose one random selection from
students. Print call_on.

In [27]:
call_on = np.random.choice(students)
print(call_on)

James Bond


Create a variable named breakout_groups and use it to choose a random
sampling from students that is 3 rows, 4 columns in size. Print breakout_groups and examine the results – would this be an effective way to
assign breakout groups? Why or why not? Add a comment to the cell with your
response.

In [30]:
breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups) 
# This is not an effective way to assign breakout groups because for each list, 
# names are repeatedly used and we can not have one person in separate meetings.

[['James Bond' 'Stefhanie' 'Dahlia' 'Brandon']
 ['Kevin' 'Stefhanie' 'Luis' 'Kevin']
 ['Hritik' 'Kevin' 'Hritik' 'Brandon']]


Create a variable named call_on_weighted and use it to choose make five
random selections from students, but this time assign different probability values
that will determine how likely each student is to be selected. At least one student
should have a zero likelihood of being called on, and at least one student should
have a 30% likelihood of being called on. Distribute other probability values as you
choose, and in a comment, explain the p values you assigned to each student. Print
call_on_weighted.

In [35]:
call_on_weighted = np.random.choice(students, 
                                    p=[.05, .05, .05, .05, .05, .05, .1, .1, .1, 0, .1, .3]
                                    ,size=(5))
# half of students were assigned a .05 probability to eventually add up to whole sum of 1,
# the rest were .1 for the same reason. the ultimate goal however was to get a value
# for everyone to be randomly selected.

print(call_on_weighted)

['Jeremiah' 'Jeremiah' 'Edmund' 'James Bond' 'Stefhanie']


## Generating a Normal Distribution

Create a variable named bell_curve and assign it a random distribution for
which the mean (peak of the curve) is 10, the standard deviation is 5, and the size of
the returned array is 4 rows by 5 columns. Print bell_curve.

In [37]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)

[[16.03307993  7.53119179 10.748038    9.66803601 11.21165333]
 [ 9.82218503 14.40733721 17.86779962  8.10634523 10.86949441]
 [10.74908059  9.8299424   9.50304932 16.57155497 16.95899268]
 [15.46297662  3.12169574 12.20961231  8.05666892 11.50138713]]
