# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np

## Sample Arrays

In a code cell, create five variables containing random sample arrays to work with,
copying over the expressions you used for variables r_1 through r_5 in the
notebook for Exercise 1.B (NumPy Random).

In [2]:
r_1 = np.random.randint(1, 20, size=(2))
r_2 = np.random.randint(1, 20, size=(1, 2))
r_3 = np.random.rand(2, 1)
r_4 = np.random.randint(20, 100, size=(4, 5))
r_5 = np.random.rand(4, 5)

## Permutations

First, print the current value of r_4.

In [3]:
print(r_4)

[[54 74 42 72 32]
 [52 96 44 56 78]
 [29 65 89 63 66]
 [23 39 54 81 79]]


Use np.random.shuffle to shuffle the values in r_4. Then print r_4 again to view
the results.

In [4]:
np.random.shuffle(r_4)
print(r_4)

[[23 39 54 81 79]
 [54 74 42 72 32]
 [52 96 44 56 78]
 [29 65 89 63 66]]


Looking at the results of the previous code block, how were the elements of the
array shuffled? Add a markdown cell to describe what you find.

    The elements of the array were shuffled by row and not by order of numbers. Essentially the sets stayed the same, just different order.

 Create a new variable named new_shuffle, and assign it the value of a random
permutation of r_4. Print new_shuffle, and then print r_4 again to compare
values.

In [5]:
new_shuffle = np.random.permutation(r_4)
print(new_shuffle)

[[23 39 54 81 79]
 [29 65 89 63 66]
 [52 96 44 56 78]
 [54 74 42 72 32]]


Add a markdown cell and briefly describe in your own words, when would you use
shuffle versus permutation?

    You would use shuffle when you want absolute 'randomness' where the possibility of repeating the same sequence is possible. Permutation allows for 'randomness' to occur but excludes its existing variation; no repitition.

## Mathematical Operations

Print r_1 and r_2 as starting values, and also print the shape of each using the
.shape attribute. Then print the result of r_1 plus r_2, using the add function. Also
print the shape of the result.

In [6]:
print(r_1, '\n', r_2)
print(r_1.shape,'\n', r_2.shape, '\n')
print(np.add(r_1, r_2))
print(np.add(r_1, r_2).shape)

[6 3] 
 [[6 1]]
(2,) 
 (1, 2) 

[[12  4]]
(1, 2)


Print r_1 and r_3 as starting values, and also print the shape of each using the
.shape attribute. Then print the result of r_1 plus r_3, using the add function. Also
print the shape of the result.

In [7]:
print(r_1, '\n', r_3)
print(r_1.shape,'\n', r_3.shape, '\n')
print(np.add(r_1, r_3))
print(np.add(r_1, r_3).shape)

[6 3] 
 [[0.97385982]
 [0.18122923]]
(2,) 
 (2, 1) 

[[6.97385982 3.97385982]
 [6.18122923 3.18122923]]
(2, 2)


Print r_2 and r_4 again as starting values, and also print the shape of each using
the .shape attribute. Then print the result of r_2 plus r_4, using the add function.
Also print the shape of the result.

In [8]:
print(r_2, '\n', r_4)
print(r_2.shape,'\n', r_4.shape, '\n')
print(np.add(r_2, r_4))
print(np.add(r_2, r_4).shape)

[[6 1]] 
 [[23 39 54 81 79]
 [54 74 42 72 32]
 [52 96 44 56 78]
 [29 65 89 63 66]]
(1, 2) 
 (4, 5) 



ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

Create an expression to illustrate what happens when you add r_1 and r_4. What
is the error message? How about adding r_2 or r_3 to r_4? Add a comment to the
cell with your findings.

In [ ]:
print(np.add(r_1, r_4))
# When adding r_1 - r_3 to r_4, we get a valueError because the shapes are not similar enough to be added together.

Show what happens if you add np.array([1]) to r_4.

In [ ]:
print(np.add(np.array([1]), r_4))

Show what happens if you add np.array([[1]]) to r_4.

In [9]:
print(np.add(np.array([[1]]), r_4))

[[24 40 55 82 80]
 [55 75 43 73 33]
 [53 97 45 57 79]
 [30 66 90 64 67]]


Show what happens if you add np.array([1,1,1,1,1]) to r_4.

In [10]:
print(np.add(np.array([1,1,1,1,1]), r_4))

[[24 40 55 82 80]
 [55 75 43 73 33]
 [53 97 45 57 79]
 [30 66 90 64 67]]


What happens if you add np.array([[1],[1]]) to r_4? Add a comment to the
cell with the error message this produces.

In [11]:
print(np.add(np.array([[1],[1]]), r_4))
# we get a valueError because the shapes are not similar enough to be added together.

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

Add a markdown cell, and in your own words, explain how broadcasting works to
combine the values of two arrays. Using the add function, what gets added to what?
What determines the shape of the resulting array?

    Using np.add adds singular values to a whole array and when adding 1D arrays to multi-dimensional arrays, the amount of columns must match between the two arrays. If adding two 2-D arrays, the number of rows in the second array must match the number of columns in the first array. Almost like a matrix. What determines the shape of the array is the shape of the two arrays being added as they must match each other in shape. If there is a shape smaller than the other, it must have a matching number of columns and a singular row. If it is a singular value, it will get stretched/duplicated to match the larger array.

## Rounding

Print r_3 to display the values you’ll be working with for the next few cells.

In [12]:
print(r_3)

[[0.97385982]
 [0.18122923]]


Round the values in r_3 using trunc.

In [13]:
print(np.trunc(r_3))

[[0.]
 [0.]]


Round the values in r_3 using fix.

In [14]:
print(np.fix(r_3))

[[0.]
 [0.]]


Round the values in r_3 using floor.

In [15]:
print(np.floor(r_3))

[[0.]
 [0.]]


Round the values in r_3 using ceil.

In [16]:
print(np.ceil(r_3))

[[1.]
 [1.]]


Round the values in r_3 using round, to 2 decimal places.

In [17]:
print(np.round(r_3, 2))

[[0.97]
 [0.18]]


## Cumulative Operations

  Print r_4 to display the values you’ll be working with for the next few cells.

In [18]:
print(r_4)

[[23 39 54 81 79]
 [54 74 42 72 32]
 [52 96 44 56 78]
 [29 65 89 63 66]]


Print the sum of all values in r_4.

In [19]:
print(np.sum(r_4))

1188


Print the sum of elements along the 0 axis for r_4.

In [20]:
print(np.sum(r_4, axis=0))

[158 274 229 272 255]


Print the sum of elements along the 1 axis for r_4.

In [21]:
print(np.sum(r_4, axis=1))

[276 274 326 312]


Print the cumulative sum (rolling total) of values in r_4.

In [22]:
print(np.cumsum(r_4))

[  23   62  116  197  276  330  404  446  518  550  602  698  742  798
  876  905  970 1059 1122 1188]


Print the cumulative sum (rolling total) of values along the 0 axis for r_4.

In [23]:
print(np.cumsum(r_4, axis=0))

[[ 23  39  54  81  79]
 [ 77 113  96 153 111]
 [129 209 140 209 189]
 [158 274 229 272 255]]


## Grocery Problem

Create two new variables, bag1 and bag2. The first variable represents the
contents of a grocery bag, which contains two vegetables, three fruits, four boxes of
snacks, and no beverages. The second variable represents another grocery bag,
which contains no fruits, four vegetables, two beverages, and one box of snacks.
Assign an appropriate array to each variable that represents how many of each
category of item are in each bag. Print bag1 and bag2.

In [26]:
bag1 = np.array([['carrots' , 'cucumbers', None, None], 
                 ['apples', 'mangos', 'bananas', None], 
                 ['doritos', 'takis', 'snickers', 'popcorn'],
                 [None, None, None, None]])

bag2 = np.array([[None, None, None, None],
                 ['lettuce', 'pickles', 'celery', 'tomatos'], 
                 ['coca-cola', 'coconut water', None, None], 
                 ['sour patch candies', None, None, None]])
print(bag1)
print(bag2)

[['carrots' 'cucumbers' None None]
 ['apples' 'mangos' 'bananas' None]
 ['doritos' 'takis' 'snickers' 'popcorn']
 [None None None None]]
[[None None None None]
 ['lettuce' 'pickles' 'celery' 'tomatos']
 ['coca-cola' 'coconut water' None None]
 ['sour patch candies' None None None]]


Write an expression to calculate the total number of items in each bag, and print the
result in the form of a sentence: The first bag contains __ items, and the second bag
contains ___ items.

In [39]:
num_of_items = lambda x: [row[row != None].size for row in x]
print(f'The first bag contains {np.sum(num_of_items(bag1))} items, and the second bag contains {np.sum(num_of_items(bag2))} items.')

The first bag contains 9 items, and the second bag contains 7 items.


In [59]:
comb = np.add(num_of_items(bag1), num_of_items(bag2))
print(comb)
print(f'There are {comb[0]} vegetables, {comb[1]} fruits, {comb[2]} boxes of snacks, and {comb[3]} beverages in the two grocery bags')

[2 7 6 1]
There are 2 vegetables, 7 fruits, 6 boxes of snacks, and 1 beverages in the two grocery bags


## Teamwork

The scenario for this set of
problems is that you are volunteering with a voter registration campaign, and you
have been asked to oversee a squad of door-knockers. There are three people on
your team: Ali, Ben, and Carla. Your squad went out to knock on doors each evening
last week, Monday through Friday, and now you are assembling that data.

Ali reported knocking on 5 doors on Monday, 4 on Tuesday, 6 on Wednesday, 4 on
Thursday, and 2 on Friday. Create a variable holding an array of these values.

In [63]:
ali = np.array([5, 4, 6, 4, 2])

Ben missed Monday because he was out of town. He reported knocking on 5 on
Tuesday, 5 on Wednesday, 3 on Thursday, and 4 on Friday. Create a variable holding
an array of Ben’s values.

In [60]:
ben = np.array([np.nan, 5, 5, 3, 4])

Carla reported knocking on 3 doors on Monday, 6 on Tuesday, 3 on Thursday, and 4
on Friday. She was sick on Wednesday so missed that day. Create a variable
holding an array of Carla’s values.

In [61]:
carla = np.array([3, 6, np.nan, 3, 4])

Compile the values reported by Ali, Ben, and Carla into a single array containing all
door-knocks for the week, as all_knocks. Print the resulting array.

In [72]:
all_knocks = np.array([ali, ben, carla])
print(all_knocks)

[[ 5.  4.  6.  4.  2.]
 [nan  5.  5.  3.  4.]
 [ 3.  6. nan  3.  4.]]


Use all_knocks to calculate the total number of doors that each person knocked
on for the week, and also the total number of doors that the group collectively
knocked on. Print the results.

In [75]:
print('Total number of doors knocked by each person:', np.nansum(all_knocks, axis=1))
print('Total doors knocked on in the week by everyone:', np.nansum(all_knocks))

Total number of doors knocked by each person: [21. 17. 16.]
Total doors knocked on in the week by everyone: 54.0


The organization you’re working with estimates that for every two door-knocks, one
of those people will actually turn out to vote. For your report to the organization,
what is the rolling total of estimated votes that your group was able to turn out, day
by day for last week? (Hint: Start with the rolling total by day, then multiply that array
by an appropriate value to get the result.)

In [82]:
total_votes = np.nansum(all_knocks, axis=0)
total_votes = total_votes * .5
print(total_votes)

[4.  7.5 5.5 5.  5. ]
